const url= "http://localhost:5000/" //Takes localhost url to fetch in notes.json
const form= document.getElementById("note-form")
let message= document.querySelector("h2")
const userInput= document.getElementById("note-input")
const addBtn= document.getElementById("add-btn")
const noteList= document.getElementById("note-list")

function getNotes(){
    return JSON.parse(localStorage.getItem("notes")) || [] //Return an empty list if there arent saved notes
}

function saveNote(notes){
    localStorage.setItem("notes", JSON.stringify(notes)) //Convert a js string to a json one to save it
}

async function saveJSON(notes){
    const date= new Date().toLocaleString().slice(0, 8) //Takes date and hour in local format
    const hour= new Date().toLocaleString().slice(10, 14)
    const lastNote= notes.at(-1) //Takes last note from local storage array to add it to json
    if (!lastNote){
        return
    }
    else{
        const noteToAdd= { //Object with note data to use post method
            "content": lastNote,
            "date": date,
            "hour": hour,
        }
        await fetch(`${url}notes`, { //Aims on notes.json
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(noteToAdd)
        })
    }
}

async function deleteNote(noteID){
    await fetch(`${url}notes/` + noteID, { 
        method: "DELETE" //Uses ID automatically generated by json server to filter it
    })
}

async function editNote(newContent, noteToUpdate){
    const newDate= new Date().toLocaleString().slice(0, 8)
    const newHour= new Date().toLocaleString().slice(10, 14)
    const updatedNote= { //Same method used in saveJSON(), but specifying put method
        "content": newContent, //Overwrites note content and date/hour
        "date": newDate,
        "hour": newHour,
    }
    await fetch(`${url}notes/` + noteToUpdate, { //Uses note ID to filter it again
        method: "PUT",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(updatedNote)
    })
}

addBtn.addEventListener("click", async (e) => {
    e.preventDefault() //Prevents page refresh and onscreen data loss 
    const note= userInput.value.trim() //Remove spaces to manage empty imputs
    if (note !== ""){
        const savedNotes= getNotes()
        savedNotes.push(note) //savedNotes as a empty list to add user notes with push method
        saveNote(savedNotes)
        await saveJSON(savedNotes)
        await showNotes()
        message.textContent= `Note sucessfully added.`
        message.classList.remove("error-deleted")
        message.classList.remove("normal")
        message.classList.add("added")
        console.log("Nota agregada, laik")
        form.reset()
    }
    else{
        message.textContent= "Invalid input!"
        message.classList.remove("normal")
        message.classList.remove("added")
        message.classList.add("error-deleted")
    }
})

async function showNotes(){
    let allNotes= getNotes()
    const catchNotes= await fetch(`${url}notes`)
    const notes= await catchNotes.json() //Converts json collection to a readable object by javascript
    noteList.innerHTML= "" //Clears noteList to avoid duplicated values
    notes.forEach((note, idx) => { //Note to show all inputs saved in local storage array
        const newNote= document.createElement("li") 
        noteList.appendChild(newNote) //Creates a child for each note
        newNote.innerHTML+= `<div class="note-container">
        <p>${allNotes[idx]}
        <br>Last update: ${note.hour}
        <br>${note.date}
        </p>
        <div class="btn-container">
        <button class="del-btn" type="button">Delete</button>
        <br><button class="update-btn" type="button">Update</button>
        </div>
        </div>`//Assigns class del-btn to all buttons per li
        //forEach uses allNotes array using index to iterate all notes
        //Like a zip() in Python :0
        const delBtn= newNote.querySelector(".del-btn")
        delBtn.addEventListener("click", async (e) => {
            e.preventDefault()
            message.textContent= "Note deleted from list"
            message.classList.add("normal")
            console.log("Note deleted from list")
            allNotes.splice(idx, 1) //Deletes selected note searching it by index
            const noteID= notes[idx].id
            noteList.removeChild(newNote)
            await deleteNote(noteID)
            saveNote(allNotes)
        })
        const updateBtn= newNote.querySelector(".update-btn")
        updateBtn.disabled= false
        const updateSection= document.getElementById("update-section")
        updateBtn.addEventListener("click", async (e) => {
            e.preventDefault()
            updateSection.innerHTML+= `
            <button class="update-confirm" type="submit">Save</button>
            `
            const updateConfirm= document.querySelector(".update-confirm")
            updateBtn.disabled= true
            updateConfirm.addEventListener("click", async (e) => {
                e.preventDefault()
                if(!userInput.value.trim()!==""){
                    message.textContent= "Note updated successfully"
                    message.classList.add("normal")
                    const noteToUpdate= notes[idx].id //Uses index to extract ID and edit it
                    allNotes[idx]= userInput.value //Overwrites note value in local storage
                    saveNote(allNotes)
                    try {
                        await editNote(userInput.value, noteToUpdate)
                        await showNotes()
                    } catch (error) {
                        console.log("There was an error updating note :(")
                    }
                    form.reset()
                    updateSection.innerHTML= ""
                }
                else{
                    message.textContent= "Invalid input!"
                    message.classList.add("error-deleted")
                }
            })
        })
    })
}
showNotes()